library(dplyr)
library(readxl)
gender_submission<-read.csv("Data/titanic/gender_submission.csv")
gender_submission %>% head()
test<-read.csv("Data/titanic/test.csv")
train<-read.csv("Data/titanic/train.csv")
head(train)
head(test)
str(test)
str(train)
View(test)
View(train)

qplot(data=train,x=Age,y=PassengerId,color=Survived)
