# Generated by Django 2.2.6 on 2019-11-13 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20191113_1434'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='hashtag',
            new_name='hashtags',
        ),
    ]
