# Generated by Django 2.2.6 on 2019-11-15 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ('-pk',)},
        ),
        migrations.AlterModelOptions(
            name='rating',
            options={'ordering': ('-pk',)},
        ),
        migrations.AddField(
            model_name='rating',
            name='movie_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='movies.Movie'),
            preserve_default=False,
        ),
    ]
